name: TDR Run API tests
on:
  pull_request:
  push:
    branches-ignore:
      - master
      - release-*
permissions:
  id-token: write
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
      - run: sbt scalafmtCheckAll 'graphqlValidateSchema "build" "consignmentApi"'
  setup-tests:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.generate-files.outputs.files }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
      - id: generate-files
        run: |
          FILES=$(find src/test/* -name "*Spec.scala" -type f -printf "%f\n" | sed 's/\.[^.]*$//' | jq -R -s -c 'split("\n")[:-1]')
          echo files=${FILES} >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    needs: setup-tests
    strategy:
      matrix:
        file: ${{ fromJSON(needs.setup-tests.outputs.files) }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
      - run: |
          docker build -f Dockerfile-tests -t tests .
          sbt "testOnly *${FILE}*"
        env:
          FILE: ${{ matrix.file }}
